baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Saar Medico'
theme = 'saar-custom'

[menus]
	[[menus.main]]
		order = 1
		name = 'Home'
		pageRef = '/'
		weight = 1 
	[[menus.main]]
		order = 2
		name = 'Categories'
		pageRef = '/categories'
		weight = 2 
	[[menus.main]]
		name = 'Services'
		pageRef = '/services'
		weight = 3  
